### ISSUE TITLE
CUDA 12: operation non supported in wrappers_to_cuda.h

### ISSUE THREAD

**Issue by srapacchi** [marcsous/gpuSparse#2]
Hi Mark!

I am experiencing a failure when processing 2 gpuSparse matrices on CUDA 12. The cusparseXcsrmm_wrapper function fails line 138 in wrappers_to_cuda.h with a message: operation not supported (10).

 I could not find similar issues online, but maybe it will echo someone else problems?

Thanks!
Stan

**Comment by marcsous** [comment]
Hi Stan,

Sorry for the hassle! I recently added some support for mixed real/complex on CUDA 12.4. Perhaps try gpuSparse('recompile') and cross your fingers. I can compile and run test_gpuSparse on MATLAB R2023a without problem. I also tried on R2018a but it seems to no longer compile... aargh, well I can't support that now.

This is my setup at the moment:
```
MATLAB Version: 9.14.0.2206163 (R2023a)
>> gpuDevice
                      Name: 'NVIDIA TITAN Xp'
                     Index: 1
         ComputeCapability: '6.1'
            SupportsDouble: 1
     GraphicsDriverVersion: '555.42.02'
               DriverModel: 'N/A'
            ToolkitVersion: 11.8000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152 (49.15 KB)
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 12771524608 (12.77 GB)
           AvailableMemory: 10795756066 (10.80 GB)
               CachePolicy: 'balanced'
       MultiprocessorCount: 30
              ClockRateKHz: 1582000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
           DeviceAvailable: 1
            DeviceSelected: 1
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```


Mark

**Comment by srapacchi** [comment]
Thanks Mark for the reply!
Indeed, the test_gpuSparse fails at matrix multiplication.

Here are the details:

>>gpuDevice

ans = 

  CUDADevice with properties:

                      Name: 'NVIDIA RTX 6000 Ada Generation'
                     Index: 1
         ComputeCapability: '8.9'
            SupportsDouble: 1
     GraphicsDriverVersion: '550.90.07'
               DriverModel: 'N/A'
            ToolkitVersion: 12.2000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152 (49.15 KB)
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 50994348032 (50.99 GB)
           AvailableMemory: 49609061508 (49.61 GB)
               CachePolicy: 'balanced'
       MultiprocessorCount: 142
              ClockRateKHz: 2505000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
           DeviceAvailable: 1
            DeviceSelected: 1

>> test_gpuSparse
[all tests passes up to this:]

========= Matrix-matrix multiply (cols 5) =========
A*x  (sparse)   : Elapsed time is 0.699595 seconds.
AT*y (sparse)   : Elapsed time is 0.684254 seconds.
A'*y (sparse)   : Elapsed time is 0.622379 seconds.

A*x  (gpuArray) : Elapsed time is 0.025612 seconds.
AT*y (gpuArray) : Elapsed time is 0.025270 seconds.
A'*y (gpuArray) : Elapsed time is 0.053294 seconds.

A*x  (gpuSparse): Error using  *  (line 519)

wrappers_to_cuda_11.h(138): operation not supported (10).


Error in test_gpuSparse (line 328)
        z = a*x; wait(gpuDevice);

I did recompile, to no avail. I will investigate this issue on my side as well.

Thanks!
Stan

**Comment by marcsous** [comment]
Hi Stan,

It must be the recent change. I am reverting it because in addition to this issue, the dedicated real x complex matrix multiply is 2x slower than "faking" it with 2 real  x real multiplies. Thanks for the feedback!

Mark

**Comment by srapacchi** [comment]
Issue solved. Thanks!
